name: Stryker mutation test
on: [pull_request]
jobs:
  mutation-run:
    name: Stryker run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: run Stryker
        run: npm run test:mutations